---
# favicon
favicon: 'favicon.ico'
# URL to the website
website_url: 'https://sat-data.vleermuis.tech'
website_title: "Overstory Interview Assignment"
# set to false to remove fork me banner in uppper right corner
fork_me: true

# image shown at the front of the page, this should be in /static/img
profile_image: ''
# image alt text
profile_image_alt: ''
name: 'Overstory Assignment'
# TODO: fill in stuff about this app
blurb: "blurb goes here"
