---
# favicon, can take any image type
favicon: 'favicon.ico'
# URL to the website
website_url: 'https://jessebot.work'
# domain name, or whatever you want the tab in the browser to say
website_title: "Overstory Interview Assignment"
# set to false to remove fork me banner in uppper right corner
fork_me: true


# image shown at the front of the page, this should be in /static/img
profile_image: 'my_picture.png'
# image alt text
profile_image_alt: ''
# Your name
name: 'Jesse Hitch'
# blurb about yourself
blurb: "blurb goes here"
